CREATE TYPE public.blueprint_side AS ENUM
    ('client', 'server', 'shared');

ALTER TYPE public.blueprint_side
    OWNER TO supabase_admin;


-- Table: public.blueprints

-- DROP TABLE IF EXISTS public.blueprints;

CREATE TABLE IF NOT EXISTS public.blueprints
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    name text COLLATE pg_catalog."default" NOT NULL,
    data jsonb NOT NULL,
    start boolean NOT NULL DEFAULT false,
    side blueprint_side NOT NULL DEFAULT 'client'::blueprint_side,
    CONSTRAINT blueprints_pkey PRIMARY KEY (id),
    CONSTRAINT blueprints_name_key UNIQUE (name)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.blueprints
    OWNER to supabase_admin;

GRANT ALL ON TABLE public.blueprints TO anon;

GRANT ALL ON TABLE public.blueprints TO authenticated;

GRANT ALL ON TABLE public.blueprints TO postgres;

GRANT ALL ON TABLE public.blueprints TO service_role;

GRANT ALL ON TABLE public.blueprints TO supabase_admin;

